#!/bin/bash
#

sudo apt-get update
sudo apt-get upgrade -y

# Install Docker
sudo curl -sSL https://get.docker.com | sh

# Install HomeAssistant
sudo docker run -d --name homeassistant --privileged --restart=unless-stopped -e TZ=Asia/Shanghai -v /home/pi/homeassistant:/config --network=host homeassistant/home-assistant

# Install OpenMediaVault
wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash

# Installing OpenJDK 8:
sudo apt-get install openjdk-8-jre-headless -y

# Installing MongoDB:
echo "deb http://archive.raspbian.org/raspbian buster main contrib non-free rpi" | sudo tee /etc/apt/sources.list.d/raspbian-archive.list
sudo apt-get update
sudo apt-get install mongodb -y

# OPTION:check if mongodb service is running:
#sudo systemctl status mongodb.service

# Installing UniFi Network Application:
#sudo apt-get install ca-certificates apt-transport-https gnupg -y
# OR:	
sudo apt-get install ca-certificates apt-transport-https -y
	
sudo wget -O /etc/apt/trusted.gpg.d/unifi-repo.gpg https://dl.ui.com/unifi/unifi-repo.gpg
echo 'deb https://www.ui.com/downloads/unifi/debian stable ubiquiti' | sudo tee /etc/apt/sources.list.d/100-ubnt-unifi.list
sudo apt-get update
sudo apt-get install unifi -y
